apiVersion: v1
kind: Service
metadata:
    name: "k8sclusterdev-dac6"
    labels:
        app: "k8sclusterdev-dac6"
spec:
    type: LoadBalancer
    ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: http
    selector:
        app: "k8sclusterdev-dac6"