version: "3.7"
services:
  dtb:
    build: ./postgres
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  back:
    build: ./nodejs-backend
    ports: 
      - "8080:8080"
    depends_on: 
      dtb:
        condition: service_healthy

    
  front:
    build: ./code
    ports: 
      - "8081:8081"




