on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: containerregistryprivate.azurecr.io
        username: ${{ secrets.acr_containerregistryprivate_username }}
        password: ${{ secrets.acr_containerregistryprivate_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/SI-gnequipe/projet/nodejs-backend" -f  "SI-gnequipe/projet/nodejs-backend/Dockerfile" -t containerregistryprivate.azurecr.io/k8sclusterdev:${{ github.sha }} --label dockerfile-path=SI-gnequipe/projet/nodejs-backend/Dockerfile
        docker push containerregistryprivate.azurecr.io/k8sclusterdev:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_k8sclusterdev_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep k8s-cluster-devad3a | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace k8s-cluster-devad3a`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: k8s-cluster-devad3a
        container-registry-url: containerregistryprivate.azurecr.io
        container-registry-username: ${{ secrets.acr_containerregistryprivate_username }}
        container-registry-password: ${{ secrets.acr_containerregistryprivate_password }}
        secret-name: k8sclusterdedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: k8s-cluster-devad3a
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          containerregistryprivate.azurecr.io/k8sclusterdev:${{ github.sha }}
        imagepullsecrets: |
          k8sclusterdedockerauth
